name: Build with DevkitPro
on:
  push:
  workflow_dispatch:
jobs:
  wii:
    name: Build Wii
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitppc:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup grrlib
        run: |
          export DEVKITPRO=/opt/devkitpro
          export DEVKITPPC=${DEVKITPRO}/devkitPPC
          git clone https://github.com/GRRLIB/GRRLIB.git
          cd GRRLIB
          make -C GRRLIB clean all install
          cd ../
          rm -rf GRRLIB/
          # mkdir -p $DEVKITPRO/portlibs/ppc/
          # cp libGRRLIB.a $DEVKITPRO/portlibs/ppc/
          # cp -r GRRLIB $DEVKITPRO/portlibs/ppc/include/
      - name: Build all wii projects
        run: |
            export DEVKITPRO=/opt/devkitpro
            export DEVKITPPC=${DEVKITPRO}/devkitPPC
            failed=()
            for d in */; do
              (
                echo "Building $d"
                cd "$d" || { echo "Failed to cd into $d"; exit 1; }
                if make; then 
                  cp *.dol ../ 2>/dev/null 
                  cp *.elf ../ 2>/dev/null 
                  cp *.bin ../ 2>/dev/null 
                else
                  echo "✘ FAILED: $d did not build" 
                  failed+=("$d")
                fi
              ) &
            done
            wait
            printf "Failed builds:\n%s\n" "${failed[@]}"
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
            name: wii-build
            path: |
                ./*.dol
                ./*.elf
                ./*.bin
